### ISSUE TITLE
proc-macro crate build data is missing dylib path

### ISSUE THREAD

**Issue by Georges760** [leighleighleigh/esp-rs-nix#4]
in VSCode, when using `"nixEnvSelector.nixFile": "${workspaceFolder}/shell.nix"` to leverage the shell.nix file, the expansion of  many proc-macro complain about dylib path missing.

Seen with:
- #[esp_hal_embassy::main]
- #[embassy_executor::task]
- debug!()

(but while building within the nix-shell, everything is fine....)

**Comment by leighleighleigh** [comment]
I've had issues with VSCode nix-shell integration too - I'll let you know if I find a fix.... Sometimes launching VSCode from a nix-shell terminal helps.

**Comment by Georges760** [comment]
found a solution: need to install `vscode-fhs` nixpkgs instead of `vscode` !!!

**Comment by leighleighleigh** [comment]
oh cool, I'll try that out, thanks!
